#!/bin/bash
# supplied info from "dump -F":
# $1 = filename
# $2 = sequence number

NUM=$(($2+1))
RECORD_BIN="/usr/bin/dvdrecord dev=0,0,0 fs=64M speed=2 "
CD_CAPACITY=4300
TSIZE="$(echo "$CD_CAPACITY*1024*1024" | bc -l )"
echo "Please insert the next DVD (No. $NUM)"
ANSWER=""
while [ "$ANSWER" != "y" ] ; do
	read -p "Is the DVD ready? (y/n)" ANSWER
	if [ "$ANSWER" == "y" ] ; then
		$RECORD_BIN -blank=fast
		$RECORD_BIN -dao -eject -pad -tsize=$TSIZE -data $1 &
		exit 0
	elif [ "$ANSWER" == "n" ] ; then
		EXIT=""
		read -p "Do you really want to exit? (y/n)" EXIT
		if [ "$EXIT" == "y" ] ; then
			exit 1
		fi
	fi
done
